# Generated by Django 5.1.6 on 2025-02-09 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('album', models.CharField(max_length=300)),
                ('genre', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('tracks', models.TextField()),
                ('lineup', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='img/covers/')),
                ('band_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='album_band', to='album.band')),
            ],
        ),
    ]
