# Generated by Django 5.1.6 on 2025-02-12 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_alter_album_options_album_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={},
        ),
        migrations.RemoveField(
            model_name='album',
            name='created_at',
        ),
    ]
