# Generated by Django 5.1.6 on 2025-02-13 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_genre_alter_album_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='band_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='album', to='album.band'),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='album', to='album.genre'),
        ),
        migrations.RemoveField(
            model_name='album',
            name='tracks',
        ),
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='album',
            name='tracks',
            field=models.ManyToManyField(related_name='album', to='album.tracks'),
        ),
    ]
