# Generated by Django 5.1.6 on 2025-02-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_tracks_alter_album_band_name_alter_album_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='tracks',
        ),
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Tracks',
        ),
        migrations.AddField(
            model_name='album',
            name='tracks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
